### ISSUE TITLE
Property 'tracking' is missing in type...

### ISSUE THREAD

**Issue by dutzi** [nytimes/react-tracking#122]
Using TypeScript with react-tracking we encountered the following error for each component wrapped by `track()`

```
Property 'tracking' is missing in type ...
```

According to [this](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34738) the issue is with react-tracking, I tried playing around with the type definitions but couldn't find a solution. If I find any I'll update.

**Comment by tizmagik** [comment]
Hi, sorry for the troubles. 

Took a quick look at your repro case, wouldn’t the TrackingProptype go on `TrackedComponent` and not on `MyComponent`? Or am I misunderstanding the issue?
