### ISSUE TITLE
TypeError on useTracking().trackEvent()

### ISSUE THREAD

**Issue by sad-squid** [nytimes/react-tracking#155]
Using `@types/react-tracking`, the DefinitelyTyped type definitions show that the useTracking().trackEvent() method's [return type is explicitly defined as `any`]((https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-tracking/index.d.ts#L11) ). Because this raises linting warnings and errors if using `@typescript-eslint/no-unsafe-return`, I've made a requested change to the types in DefinitelyTyped - [link to pull request here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45188). 

If there is any concern / issue with the adjustment of typing from `any` to `void` please let me know! Feel free to close this issue if valid! ✅

**Comment by tizmagik** [comment]
That makes sense, thanks for catching this. I see the Definitely Typed has been merged and it looks like a good change to me, so I'll close this issue.

FWIW, we are looking to bring the TS typings in-house here. This PR is a step in that direction and your review would be appreciated! https://github.com/nytimes/react-tracking/pull/152

Thanks again!
