### ISSUE TITLE
Typescript types not up to date for V8

### ISSUE THREAD

**Issue by mattes3** [nytimes/react-tracking#173]
Hi,

the typescript types are not up to date. They correspond to version 7. They are missing the property `Track` in the object that is returned by the `useTracking()` hook.

Could you please add that?

Thanks...
Matthias

**Comment by tizmagik** [comment]
Thanks, dupe of #172 -- TypeScript types via Definitely Typed are a community-driven effort currently. Although we do have plans to rewrite the internals to TypeScript and thus export type definitions directly (see #152 for WIP or if you'd like to contribute)
