### ISSUE TITLE
Track PageView

### ISSUE THREAD

**Issue by AdsonCicilioti** [nytimes/react-tracking#175]
Is possible track Pageviews?

I'm trying onLoad event but on production (vercel) the page static obfuscate new pagelods counts.

**Comment by tizmagik** [comment]
It should be possible assuming you have React runtime on the frontend and you're not just rendering to static markup. If you have an example repro I'd be happy to take a look.

**Comment by tizmagik** [comment]
Closing for now. Feel free to reopen if you have a repro with some more context. Thanks!
