### ISSUE TITLE
React 18 peer dependency

### ISSUE THREAD

**Issue by aldrakos** [nytimes/react-tracking#201]
Hello and thanks for the awesome job on this library!

Wanted to ask if there are any plans to support React 18, even just by adding the peer dependency and not fully opting in the new React18 features.

**Comment by tizmagik** [comment]
Sure yea, it should be fully compatible. PRs welcome!

**Comment by aldrakos** [comment]
Thanks! Will look into that then!

**Comment by anna-rusk** [comment]
@aldrakos Did you ever try out React 18? I am finding that it is not compatible

**Comment by anna-rusk** [comment]
I filed an issue here - https://github.com/nytimes/react-tracking/issues/218

I just upgraded react and react-dom and didn't change any tracking code and am seeing this issue
