### ISSUE TITLE
Question: How to integrate with NextJS (server-side components)

### ISSUE THREAD

**Issue by alexdelgado** [nytimes/react-tracking#228]
Hey!

It looks like you're creating a client-side context which works great in most cases, but NextJS does a lot of server-side rendering and caching so either you push `<track />` really far down, or lose out on some of NextJS's caching. 

Is that right?

How are you integrating the two?

**Comment by visualjeff** [comment]
Alex, Have you had any success with Nextjs 14 and this package since this creating this issue?

**Comment by alexdelgado** [comment]
Nope, we ended up building our own data layer that doesn't use react contexts. While most of the data layer does work "client side", we're still leveraging server-side rendering using the [Script tag ](https://nextjs.org/docs/app/building-your-application/optimizing/scripts) with `onReady` functions.

**Comment by tizmagik** [comment]
So most everything [happens within a useEffect](https://github.com/nytimes/react-tracking/blob/main/src/useTrackingImpl.js) and the context should be getting re-established client-side so the server-side ends up being mostly a no-op. 

We used this with a server-rendered framework at NYT, so it should work fine in an SSR mode.

What issues were you running into @alexdelgado ?

**Comment by alexdelgado** [comment]
Honestly it turned out to be a mis-understanding of how inter-leaving works in Next.js I was under the impression that if you created a client-side context then everything would become client-side. It took watching some videos to understand that's not the case.
