### ISSUE TITLE
Adapt for External Analytics

### ISSUE THREAD

**Issue by ev1stensberg** [NYTimes/react-tracking#41]
Is there any plan to make the API viable for people to integrate with say Google Cloud, Google Analytics or an custom API? Currently in the stages of making an bundler that will act on tracking, and I think that this library could be super-fit for that, if one could export data from the tracking itself

What are your thoughts?

**Comment by tizmagik** [comment]
Hey thanks for your question! This library is meant to be pretty agnostic to where the data goes, you just need to define a top-level `dispatch` function that determines where it goes. We currently use it to send analytics data to Google Analytics (via pushing the data to `window.dataLayer[]`), but you could have it go anywhere, even through an API call or whatever you need.

Does that make sense? Let me know if I’m missing something, or if I could make the documentation clearer about that. I hope that’s helpful!

**Comment by ev1stensberg** [comment]
Wow, thanks! No further explanation needed, thanks for elaborating!
