### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by alloy** [NYTimes/react-tracking#44]
Hi!

I seem to recall that when we last spoke you were saying that you may be interested in hosting TypeScript type declarations inside this repository. Is that correct? If not, I’ll just move [our typings](https://github.com/craigspaeth/reaction/pull/1/files#diff-4258c676b4468a5193831f426d8f0ebf) to the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped) instead.

**Comment by tizmagik** [comment]
Hey @alloy thanks for this, this would be a very welcome contribution! 

I'd totally be up for hosting the TypeScript declarations here in this repo, but I honestly haven't worked with TypeScript before (would like to!). Do you have a branch/fork I could check out and get a feel for?

In the mean time, by all means, feel free to submit to DefinitelyTyped if you'd prefer, of course. 😁

**Comment by orta** [comment]
WRT testing the types - @lazerwalker did a good job in https://github.com/alexa-js/alexa-app/pull/266 at showing how to add tests for the d.ts

**Comment by lazerwalker** [comment]
Yep! The relevant bit is if you have a test `ts` file inside your type folder, running `dtslint` on that folder will try to compile your test file and yell at you if it fails, the same as automatically happens in the DT repo.

**Comment by alloy** [comment]
@lazerwalker @orta Nice one, thanks gents 👍 

@tizmagik For now I’ve pushed the typings to DT, as proposed, which includes the ‘tests’ that you can pull and play around with: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20011. Let me know if you have any questions.

**Comment by alloy** [comment]
In the meantime, I’ll close this ticket, as we _did_ reach an answer. We can continue to discuss, if necessary, otherwise I’ll just PR the typings and tests to this repo once #45 has been addressed.

**Comment by tizmagik** [comment]
Awesome, thanks everyone. I've merged and released #45 as `v5.0.0` 🎉 

I'll have a look at the typings in DT and play around with it, thanks again for that, much appreciated. In the mean time, feel free to open a PR whenever you have some time with the typings and tests now that #45 has landed. Cheers!
