### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by frytyler** [NYTimes/react-tracking#56]
Just noticed there is no `CONTRIBUTING.md` file to help people get started with the project. 

[Kent C Dodds](https://twitter.com/kentcdodds) talks about a great way to incorporate contributing information here: https://github.com/kentcdodds/all-contributors 

Even just a simple contributing.md file talking about setup and expectations of contributing would be helpful for anyone getting involved.

**Comment by tizmagik** [comment]
Good call! Posting now
