### ISSUE TITLE
HOC Process does not apply to methods

### ISSUE THREAD

**Issue by Sicria** [NYTimes/react-tracking#63]
I've added a HOC ``@track`` which has a ``process`` and it works great for the ``@track`` on the class, but does not apply to the methods in the class.

I'm using this to validate events before they're sent to the dataLayer and change the case on some certain attributes so it's ideal if this is applied to all events.

**Comment by tizmagik** [comment]
Thanks for the report @Sicria ! Are you able to create a reproduction case, ideally as a test case as part of the [e2e suite](https://github.com/NYTimes/react-tracking/blob/master/src/__tests__/e2e.test.js)?

**Comment by tizmagik** [comment]
@Sicria is your use case that you have a `process` function defined on some nested component deep within the app? I think the `process` function is only meant to be defined on the top-level app wrapper, although I think we can consider supporting your use case.

Let me know if you can clarify and/or submit a failing test case and I can look into it more.

**Comment by Sicria** [comment]
@tizmagik Sorry about the delay.

I've got a container component wrapped around the entire app which has a ``process`` function to modify certain values etc.

Then within the app there's children components which have ``@track`` but no ``process``, when an event is fired from one of these it's not passed to the higher ``process`` function, but if I add a ``process`` function to the child component, it catches the event, but also throws an error in the console about having 2 ``process`` present on the same page.

Sorry I'm not able to create a test case at the moment, if you still require further details I can create a gist with some basic code to demonstrate my use-case.

**Comment by Sicria** [comment]
Ended up solving my use-case when implementing this on another project.
Solution can be found in https://github.com/NYTimes/react-tracking/issues/75.
