### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by Sicria** [NYTimes/react-tracking#75]
Is it possible to run all events through a formatter function before they're sent to the dataLayer?

A use-case for this is that I would like to ensure that certain field values are all formatted the same. This means that in some instances "search" & "Search" is split into two different events.

If a formatter was applied to those, you could enforce a lowercase standard to all events where certain fields are formatted differently to ensure consistency.

Proposed implementation:
```
@track({ category: 'App' }, {
  formatter: trackingData => ({
    ...trackingData,
    label: (trackingData.label || '').toLowerCase(),
    value: trackingData.value || null,
  }),
})
```

I'd assume it would work like ``process`` where there's only 1 formatter allowed but I suppose someone could have another use-case which would require them to format their events on a component by component basis.

**Comment by Sicria** [comment]
**Update:** Found a way to achieve this by overwriting the ``dispatch`` function.

```
@track({ category: 'App' }, {
  dispatch: (data) => {
    // Push the data into the tracking layer
    (window.dataLayer = window.dataLayer || []).push({
      ...data,
      label: (data.label || '').toLowerCase(),
      value: data.value || null,
    });
  },
})
```

**Comment by tizmagik** [comment]
Glad you found a solution @Sicria -- feel free to submit a documentation update PR to add this use case if you think it would be helpful to others 😁
