### ISSUE TITLE
Documentation: FooComponent is missing in the sample 

### ISSUE THREAD

**Issue by anandshanbhag** [NYTimes/react-tracking#78]
In the "**Usage on Stateless Functional Components**" section of readme, you have created a component with the name "**FooPage**", but while creating HOC thorugh "track" you have mentioned "**FooComponent**".
 
`export default track({
  page: 'FooPage'
})(FooComponent);`

It should be the following;

`export default track({
  page: 'FooPage'
})(FooPage)`

**Comment by tizmagik** [comment]
Fixed in https://github.com/NYTimes/react-tracking/pull/80 thanks for the report!
