### ISSUE TITLE
Duplicated data entries and parent components challenges

### ISSUE THREAD

**Issue by daniel-winter** [NYTimes/react-tracking#85]
Dear NYTimes team, dear @tizmagik,

we are currently working on a relaunch of our online-shop/platform with ReactJs. For tracking purposes we want to use your powerful, light and well implemented plugin. Before we go online, we have a few challenges to overcome. Therefore, we would be very happy if you could share your experiences with us:

Specifically, since ReactJs's lifecycle calls methods more than only once to varify if there are dom-changes, the tracking decorator is triggered more than once too. This results in duplicated entries on the dataLayer. Do you have any solution for this? Or do get the duplicate data filtered by you data analyst? Do get the data filtered by comparing milliseconds in timestamps?

The second challenge for which we do not yet have a solution: Tracking parent components. For a better explanation here is a short example: We display multiple products on one page grouped by sliders named "recommendations" and "other-users-liked". It may happen that one product appears in both sliders at the same time. A click on the product then triggers a tracking action. Because we have component based architecture, the product component doesn't know anything from the parent slider. But we do need to get this information in which slider the product has been to ensure proper analytics on which slider is more successful. Did you have similar problems? If so, how did you solve this?

We would be very happy and grateful if you could share your experiences with us.

Best wishes,
Daniel

**Comment by daniel-winter** [comment]
Hi @tizmagik, thank you for your detailed answer.

**Duplicate data**

We're evaluating our code right now. This takes a lot of time, so I'm sorry for the delay of a proper response.

In the meantime I've another question regarding the usage of the decorator. We've currently a problem using arrow functions as event callbacks with the decorator. We're using arrow functions to prevent binding in the constructor. For example:
```
class Product extends Component {
    ... bla bla ...

    @track()
    handleClick = (event) => {
        console.log('Clicked!');
    }
    render() {
        return (
            <button onClick={this.handleClick}>Do it</button>
        );
    }
}
export default Product;
```

In this case `handleClick` does not gets executed at all. Do you have any idea on that? We have also checkout your codesandbox (https://codesandbox.io/s/pj43j286nj) and forked it here (https://codesandbox.io/s/pj43j286nj) but we haven’t found any working solution.

**Tracking parent components**

Thank you for your explanation. Indeed a nice feature! But we're facing the problem of using the same parent component more than once. Like this:
```
  <Page>
    <Slider>
      <Product uid="a" />
      <Product uid="b" />
    </Slider>
    <SomeOtherStuff />
    <Slider>
      <Product uid="a" />
      <Product uid="c" />
    </Slider>
  </Page>
```

So the context of the parent component is just 'imaginary', since both parents are the same component. But maybe we could distinguish them by adding otherwise unused props like `<Slider trackAs="recommendations">`

Nevertheless the parent decorators don't get executed on (for example) a Product „hover“ or Product „click“. So tracking which Product was clicked or hovered is possible, but at that time we're missing the information, if it was <Product uid="a" /> in Slider 1 or 2. Do you have any suggestions for that challange?

Thanks in advance!

**Comment by tizmagik** [comment]
Decorating class methods should work fine (as can be seen in the codesandbox example). Make sure you also decorate the `class` declaration itself, that's required for decorating within the class to work properly.

```js
@track() // required
class Product extends Component {
  @track({ event: 'clicked' })
  handleClick = () => {}
}
```

Also, make sure your tracking objects have data in them (at least one property for the entire tree). By default, [empty objects are not dispatched](https://github.com/NYTimes/react-tracking/blob/62901a0622a542df3bcd07f401ca2cf089700380/src/dispatchTrackingEvent.js#L2).

---

Yes, I would solve as you suggested, provide an otherwise unused prop so that the tracking context of "which" slider can be determined.

```js
@track(props => ({
  slider: props.trackAs,
}))
class Slider extends Component {}
```

Then render them as so:

```js
<Slider trackAs="recommendations" />
<Slider trackAs="otherusersliked" />
```

**Comment by rickgaurav** [comment]
```Decorating class methods should work fine (as can be seen in the codesandbox example). Make sure you also decorate the class declaration itself, that's required for decorating within the class to work properly.```
