### ISSUE TITLE
Track Hierarchy

### ISSUE THREAD

**Issue by jbadeau** [NYTimes/react-tracking#93]
Hi,

Given: a tracked component tree like:

```
App @track({app:'myApp'})
|--Page @track({page:'page1'})
    |-TabBar @track({tabbar:'tabbar1'})
       |-Tab @track({tab:'tab1'})
       |-Tab @track({tab:'tab2'})
```

When: the user selects a Tab1

Then: I would like to be able to dispatch a message like:
{event: 'myapp.page1.tabbar1.tab1'}

The current dispatch method provides an object like:

{app:'myApp', 'tab': 'tab1', page: 'myApp', tabBar:'tabBar1'}

 but I don't know the hierarchy. Is there some way I can create the hierarchy in the dispatch or pre-process

Regards
Jose

**Comment by daniel-winter** [comment]
Take a look here to the answer of @tizmagik 
https://github.com/NYTimes/react-tracking/issues/85

**Comment by jbadeau** [comment]
Hi,

My issue he is not to know which tab was clicked but to be able to reconstruct the component hierarchy. TrackingData is an object which means I cant' rely on property iteration order to reconstruct the tree.

**Comment by jbadeau** [comment]
Exactly, I don't know the order.  Humm, I will see what I can come up with in.

**Comment by jbadeau** [comment]
We have forked the project. The issues is that if a child component tracks a property with the same name as a parent component, then it is replaced via the deep merge.

deep merge:

parent: {foo: {a:1}}
child: {foo: 'dog'}
merged obj: {foo: 'dog'}

shallow append

parent: {foo: 'cat'}
child: {foo: 'dog'}
merged obj: {foo: [{a:1}, 'dog']}

the properties are merged into any array in the order of the component hierarchy. we don't want to loose properties. Developers can still merge if they want to keep the existing behavior

Cheers,
Jose

**Comment by tizmagik** [comment]
Interesting. Might be useful as an optional property to change the merge behavior at some root-level component, similar to how dispatch behavior is defined:

```js
@track({}, { dispatch, shallowAppend: true })
export default class App extends Component { ... }
```

@jbadeau if you want to contribute that back instead of maintaining a separate fork I think we can consider it here, it seems generally useful.

**Comment by jbadeau** [comment]
I def like the idea of a user configurable merge strategy. Let me refactor the code a bit to try that. As the code is maintained in a private fit repo I cannot share but I can provide a fit patch
